CREATE TABLE CONTACT
(
    ID         BIGSERIAL PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP    NOT NULL,
    UPDATED_AT TIMESTAMP    NOT NULL
)
