POST http://localhost:8080/login?username=admin&password=321321
Content-Type: application/json

###

GET http://localhost:8080/ping
Accept: application/json
X-Auth-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjIsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAka1FUWnVVV0FPdzBId0gzSTh0QjV5ZVp3VVV4RkxYdDl0TVZJcDlpVlkvM254T1ZsMFlFaC5cIixcImVuYWJsZWRcIjp0cnVlLFwiYXV0aG9yaXRpZXNcIjpbXSxcImFjY291bnROb25FeHBpcmVkXCI6dHJ1ZSxcImFjY291bnROb25Mb2NrZWRcIjp0cnVlLFwiY3JlZGVudGlhbHNOb25FeHBpcmVkXCI6dHJ1ZX0ifQ.77sy2LASAbQ6-Jl4RqMbPYMQI1SajAHaFeYTsxuWVno

###

GET http://localhost:8080/me
Accept: application/json
X-Auth-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjIsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAka1FUWnVVV0FPdzBId0gzSTh0QjV5ZVp3VVV4RkxYdDl0TVZJcDlpVlkvM254T1ZsMFlFaC5cIixcImVuYWJsZWRcIjp0cnVlLFwiYXV0aG9yaXRpZXNcIjpbXSxcImFjY291bnROb25FeHBpcmVkXCI6dHJ1ZSxcImFjY291bnROb25Mb2NrZWRcIjp0cnVlLFwiY3JlZGVudGlhbHNOb25FeHBpcmVkXCI6dHJ1ZX0ifQ.77sy2LASAbQ6-Jl4RqMbPYMQI1SajAHaFeYTsxuWVno

###
