GET http://localhost:8080/contacts

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "second contact",
  "email": "second@contact.com"
}

###

PUT http://localhost:8080/contacts/1
Content-Type: application/json

{
  "name": "first contact",
  "email": "first@company.com"
}

###

DELETE http://localhost:8080/contacts/1

###

GET http://localhost:8080/contacts/1/histories

###
