GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts
Accept: application/stream+json

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "contact",
  "email": "contact@email.com"
}

###

GET http://localhost:8080/contacts/5

###

DELETE http://localhost:8080/contacts/4

###