CREATE TABLE TB_ORDER
(
    ID         BIGSERIAL                   NOT NULL PRIMARY KEY,
    PRICE      DECIMAL(10, 2)              NOT NULL,
    STATUS     VARCHAR(255)                NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
